// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/yoyaku-kanri/SlotGrid.tsx": () => import("../components/mockups/yoyaku-kanri/SlotGrid.tsx"),
  "./components/mockups/yoyaku-kanri/WeeklyCalendar.tsx": () => import("../components/mockups/yoyaku-kanri/WeeklyCalendar.tsx")
};
